# Generated by Django 5.0.2 on 2024-02-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangloreJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChennaiJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MumbaiJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuneJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
